// Generated by CoffeeScript 1.3.3
(function() {
    'use strict';
    define(['jquery', 'ParallaxScroll', 'CodeFooter', 'ImageExpander'],
        function($, ParallaxScroll, CodeFooter, ImageExpander) {
        var exports, gVars, makeItHappen, moduleName;
        exports = {};
        gVars = {};
        moduleName = 'code_blog';

        makeItHappen = function() {
            // purchase.purchaseProduct();
            ParallaxScroll.init();
            CodeFooter.init();
            ImageExpander.init();
        };
        exports.init = function($this) {
            var $element;
            if ($this !== void 0) {
                return makeItHappen($this);
            }
            else {
                $element = $('[data-module="' + moduleName + '"]');
                return $element.each(function() {
                    return makeItHappen($(this));
                });
            }
            // $element = $('[data-module="' + moduleName + '"]');
            // if ($element.length > 0) {
            //     return $element.each(function() {
            //         return makeItHappen($(this));
            //     });
            // }
        };
        return exports;
    });

}).call(this);
