// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var $, exports, gVars, makeItHappen, makeLoops, moduleName, gVars;
    $ = require("jquery");
    exports = {};
    gVars = {
        canvasWidth: 0,
        canvasHeight: 0
    };
    moduleName = "code_footer";
    _window = $(window);
    makeLoops = function() {
        var canvas = document.getElementById('myCanvas');
        var context = canvas.getContext('2d');

        context.beginPath();
        context.moveTo(300, 0);
        context.bezierCurveTo(300, 150, 275, 200, 200, 200);
        context.bezierCurveTo(100, 200, 25, 150, 0, 100);
        context.lineTo(0,200);
        context.lineTo(300,200);
        context.lineTo(300,0);
        context.fillStyle = "blue";
        context.fill();
        context.lineWidth = 1;

        // line color
        context.strokeStyle = 'blue';
        context.stroke();

    };
    makeItHappen = function($this) {
        $section = $this.find('section');
    };
    exports.init = function($this) {
        var element;
        if ($this !== void 0) {
            return makeItHappen($this);
        }
        else {
            element = $("body").find("[data-module=\"" + moduleName + "\"]");
            return element.each(function() {
                return makeItHappen($(this));
            });
        }
    };
    return exports;
    });

}).call(this);
