// Generated by CoffeeScript 1.3.3
(function() {
    define(function(require) {
        var $, exports, gVars, makeItHappen, moduleName, gVars;
        $ = require("jquery");
        exports = {};
        gVars = {};
        moduleName = "image_expander";
        makeItHappen = function($this) {
            $img = $this.find('img');
            $img.on('click', function() {
                if ($this.hasClass('selected')) {
                    $this.removeClass('selected');
                }
                else {
                    $this.addClass('selected');
                }
            });
        };
        exports.init = function($this) {
            var element;
            if ($this !== void 0) {
                return makeItHappen($this);
            }
            else {
                element = $("body").find("[data-module=\"" + moduleName + "\"]");
                return element.each(function() {
                    return makeItHappen($(this));
                });
            }
        };
            return exports;
    });

}).call(this);
