// Generated by CoffeeScript 1.3.3
(function() {

  define(['ColorTuner', 'SocialFu', 'ParallaxScroll', "purchase"], function(ColorTuner, SocialFu, ParallaxScroll, purchase) {
    var $, exports, gVars, makeItHappen, moduleName;
    $ = require("jquery");
    exports = {};
    gVars = {};
    moduleName = "retromator";

    makeItHappen = function($this) {
        // purchase.purchaseProduct();
        ParallaxScroll.init();
        SocialFu.init();
        ColorTuner.init();
    };
    exports.init = function($this) {
        var $element;
        if ($this !== void 0) {
            return makeItHappen($this);
        }
        else {
            $element = $('[data-module="' + moduleName + '"]');
            return $element.each(function() {
                return makeItHappen($(this));
            });
        }
        // $element = $('[data-module="' + moduleName + '"]');
        // if ($element.length > 0) {
        //     return $element.each(function() {
        //         return makeItHappen($(this));
        //     });
        // }
    };
    return exports;
    });

}).call(this);
